---
&sock-shop-shipping timestamp: 2019-12-16T16-38-00-000Z
endpoints:
- !<http>
  &shippingGetShippingUsingGET domain: shipping
  port: 80
  path: /shipping
  method: GET
  headers:
  - 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
  - 'Content-Type: application/x-www-form-urlencoded'
  - 'X-Requested-With: XMLHttpRequest'
  protocol: http

- !<http>
  &shippingPostShippingUsingPOST domain: shipping
  port: 80
  path: /shipping
  method: POST
  headers:
  - 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
  - 'Content-Type: application/json'
  - 'X-Requested-With: XMLHttpRequest'
  parameters:
  - &shippingPostShippingUsingPOST_body_BODY name: body
    parameter-type: BODY
  protocol: http

- !<http>
  &shippingGetShippingByIdUsingGET domain: shipping
  port: 80
  path: /shipping/{id}
  method: GET
  headers:
  - 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
  - 'Content-Type: application/x-www-form-urlencoded'
  - 'X-Requested-With: XMLHttpRequest'
  parameters:
  - &shippingGetShippingByIdUsingGET_id_URL_PART name: id
    parameter-type: URL_PART
  protocol: http

- !<http>
  &shippingGetHealthUsingGET domain: shipping
  port: 80
  path: /health
  method: GET
  headers:
  - 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
  - 'Content-Type: application/x-www-form-urlencoded'
  - 'X-Requested-With: XMLHttpRequest'
  protocol: http